// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using WebApi.Repository;

namespace WebApi.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20180627163436_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<bool>("IsUse");

                    b.Property<int?>("ProductGradeId");

                    b.HasKey("Id");

                    b.HasIndex("ProductGradeId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("WebApi.Models.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComeFrom");

                    b.Property<string>("MadeFor");

                    b.Property<int>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductDetail");
                });

            modelBuilder.Entity("WebApi.Models.ProductGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("ProductGrade");
                });

            modelBuilder.Entity("WebApi.Models.ProdutItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProdutItem");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.HasOne("WebApi.Models.ProductGrade", "ProductGrade")
                        .WithMany("Products")
                        .HasForeignKey("ProductGradeId");
                });

            modelBuilder.Entity("WebApi.Models.ProductDetail", b =>
                {
                    b.HasOne("WebApi.Models.Product", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("WebApi.Models.ProductDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.ProdutItem", b =>
                {
                    b.HasOne("WebApi.Models.Product", "Product")
                        .WithMany("ProdutItems")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
